# Generated by Django 4.2.4 on 2023-08-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=70)),
                ('tipo_proyecto', models.CharField(max_length=70)),
                ('descripcion_proyecto', models.TextField(max_length=500)),
                ('url_demo', models.URLField(max_length=250)),
                ('url_github', models.URLField(max_length=250)),
                ('prioridad', models.PositiveIntegerField()),
            ],
        ),
    ]
