# Generated by Django 4.2.4 on 2023-08-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0002_proyecto_url_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_subject', models.CharField(blank=True, max_length=200)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
